# This workflow reuses the openHIE GitHub action for building IGs
# Initial idea by Carl Leitner, developed by Elliot Silver, available from: https://www.argentixinfo.com/archives/156
# Change log:
# v0.1.0
# 2021-06-18: publish default branches to / , other branches branches/<branch>
# 2021-11-26: reusable workflow

name: GitHub Pages build

# Controls when the action will run. 
on: []
