# This workflow uses a remote action to do some repository actions like updating the readme files

name: Call remote repo actions

# Controls when the action will run. 
on: []

jobs:
  call-update-readme:
    uses: WorldHealthOrganization/smart-base/.github/workflows/update_readme.yml@main
    with:
      repositoryOwner: ${{ github.repository_owner }}
      repositoryName: ${{ github.event.repository.name }}
